# Generated by Django 3.0.7 on 2020-07-03 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinnumber', models.CharField(max_length=200, null=True)),
                ('managername', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('nationality', models.BooleanField(null=True)),
                ('addressinfo', models.BooleanField(max_length=200, null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('ward', models.CharField(max_length=200, null=True)),
                ('village', models.CharField(max_length=200, null=True)),
                ('subvillage', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('road', models.CharField(max_length=200, null=True)),
                ('plotnumber', models.CharField(max_length=200, null=True)),
                ('blocknumber', models.CharField(max_length=200, null=True)),
                ('housenumber', models.CharField(max_length=200, null=True)),
                ('pobox', models.CharField(max_length=200, null=True)),
                ('postalcity', models.CharField(max_length=200, null=True)),
                ('phonenumber', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('mname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password1', models.CharField(max_length=200, null=True)),
                ('password2', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousLicenseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensenumber', models.CharField(max_length=200, null=True)),
                ('date_issue', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiredate', models.DateTimeField(auto_now_add=True, null=True)),
                ('feepaid', models.FloatField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('businessdetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.BusinessDetails')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer'),
        ),
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('mname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('dob', models.DateTimeField(auto_now_add=True, null=True)),
                ('nationality', models.BooleanField(null=True)),
                ('addressinfo', models.BooleanField(null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('ward', models.CharField(max_length=200, null=True)),
                ('village', models.CharField(max_length=200, null=True)),
                ('subvillage', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('road', models.CharField(max_length=200, null=True)),
                ('plotnumber', models.CharField(max_length=200, null=True)),
                ('blocknumber', models.CharField(max_length=200, null=True)),
                ('housenumber', models.CharField(max_length=200, null=True)),
                ('pobox', models.CharField(max_length=200, null=True)),
                ('postalcity', models.CharField(max_length=200, null=True)),
                ('phonenumber', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
            ],
        ),
    ]
