# Generated by Django 3.0.8 on 2020-07-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='terms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
    ]
