# Generated by Django 3.0.8 on 2020-07-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200706_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='terms',
        ),
    ]
