# Generated by Django 3.0.8 on 2020-08-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20200803_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.ApplicantDetails'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='addressinfo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='nationality',
            field=models.CharField(choices=[('Tanzanian', 'Tanzanian'), ('Foreigner', 'Foreigner')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='previouslicensedetails',
            name='date_issue',
            field=models.DateTimeField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='previouslicensedetails',
            name='expiredate',
            field=models.DateTimeField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='previouslicensedetails',
            name='feepaid',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
