# Generated by Django 3.0.8 on 2020-08-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20200808_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='applicant',
        ),
    ]
