# Generated by Django 3.0.8 on 2020-08-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_businessdetails_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
