# Generated by Django 3.0.8 on 2020-08-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20200811_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='applicatsetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.ApplicantDetails'),
        ),
    ]
