# Generated by Django 3.0.8 on 2020-08-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_businessdetails_applicatsetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='applicatsetails',
        ),
    ]
