# Generated by Django 3.0.8 on 2020-08-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_businessdetails_applicatsetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previouslicensedetails',
            name='date_issue',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='previouslicensedetails',
            name='expiredate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
