# Generated by Django 3.0.8 on 2020-08-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20200815_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer'),
        ),
    ]
