# Generated by Django 3.0.8 on 2020-08-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_category_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
