# Generated by Django 3.0.8 on 2020-09-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_businesscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='price',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
