# Generated by Django 3.0.8 on 2020-09-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20200904_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='businesscategory',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
