# Generated by Django 3.0.8 on 2020-09-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20200904_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='businessdetails',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer'),
        ),
    ]
