# Generated by Django 3.0.8 on 2020-09-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_auto_20200908_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer'),
        ),
    ]
