# Generated by Django 3.0.8 on 2020-09-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20200911_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocuments',
            name='men',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer'),
        ),
    ]
