# Generated by Django 3.0.8 on 2020-09-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_auto_20200911_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadDocuments',
        ),
    ]
