# Generated by Django 3.0.8 on 2020-09-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_delete_uploaddocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf1', models.FileField(upload_to='uploaddocuments/pdf/')),
                ('pdf2', models.FileField(upload_to='uploaddocuments/pdf/')),
                ('pdf3', models.FileField(upload_to='uploaddocuments/pdf/')),
                ('pdf4', models.FileField(upload_to='uploaddocuments/pdf/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
            ],
        ),
    ]
