# Generated by Django 3.0.8 on 2020-09-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_uploaddocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocuments',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
