# Generated by Django 3.0.8 on 2020-09-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_auto_20200912_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddocuments',
            name='status',
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='pdf1',
            field=models.FileField(upload_to='uploaddocuments/pdf/'),
        ),
    ]
