# Generated by Django 3.0.8 on 2020-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_auto_20200912_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddocuments',
            name='pdf1',
        ),
        migrations.RemoveField(
            model_name='uploaddocuments',
            name='pdf2',
        ),
        migrations.RemoveField(
            model_name='uploaddocuments',
            name='pdf3',
        ),
        migrations.RemoveField(
            model_name='uploaddocuments',
            name='pdf4',
        ),
        migrations.AddField(
            model_name='uploaddocuments',
            name='authority',
            field=models.FileField(null=True, upload_to='uploaddocuments/pdf/'),
        ),
        migrations.AddField(
            model_name='uploaddocuments',
            name='citizenship',
            field=models.FileField(null=True, upload_to='uploaddocuments/pdf/'),
        ),
        migrations.AddField(
            model_name='uploaddocuments',
            name='rent',
            field=models.FileField(null=True, upload_to='uploaddocuments/pdf/'),
        ),
        migrations.AddField(
            model_name='uploaddocuments',
            name='tax',
            field=models.FileField(null=True, upload_to='uploaddocuments/pdf/'),
        ),
    ]
